version: '2'

services:
    nginx_sipac:
        image: nexus.prod.uci.cu/nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php_sipac
        volumes:
            #- ..\..\PhpstormProjects\sipac_2.4:/var/www/html
            - ./logs/nginx/:/var/log/nginx
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/sipac_2.4.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx.pem:/etc/ssl/certs/nginx.pem
            - ./conf/nginx.key:/etc/ssl/private/nginx.key
    php_sipac:
        image: nexus.prod.uci.cu/rmolinet/sipac-php-alpine:2.1
        volumes:
            #- ..\..\PhpstormProjects\sipac_2.4:/var/www/html
            - ./conf/php.ini:/usr/local/etc/php/php.ini
            #- ./conf/profiler_files:/usr/local/reportes_kcachegrind
    postgres_sipac:
        image: nexus.prod.uci.cu/postgres:alpine
        ports:
            - "5432:5432"
        volumes:
            #- ./conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
            - data_postgresql:/var/lib/postgresql/data
            - binarios_postgres:/usr/local/bin
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
    pgadmin_postgres:
            image: nexus.prod.uci.cu/rmolinet/sipac-pgadmin4:1.1
            ports:
                - "8080:5050"
            depends_on:
                - postgres_sipac
            volumes:
                - binarios_postgres:/usr/local/bin/postgres_binaries
                - ./conf/pgadmin4_storage:/var/lib/pgadmin/storage
            environment:
                DEFAULT_USER: admin@uci.cu
                #DEFAULT_PASSWORD: admin
volumes:
    data_postgresql:
    binarios_postgres: